import { SiteConfig } from '../interfaces';

export const SITES: Record<string, SiteConfig> = {
  'asajoyeria.com': {
    apiDomain: 'https://be.asajoyeria.com/',
    s3Url: 'https://asajoyeriafiles.s3.eu-central-1.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 9, // -->  000000001
    suffixLength: 10, // -> 0000002202  --> 000000001-0000002202
    priceList: 'PD',
    siteName: 'Asa Joyería',
    defaultDescription: 'Pide en nuestra web. Paga fácil con tarjeta o en efectivo.',
    defaultImage: 'https://asajoyeria.com/logo.webp',
    targetUrl: 'https://asajoyeria.com',
  },
  'www.intensoperfumeshn.com': {
    apiDomain: 'https://be.intensoperfumeshn.com/',
    s3Url: 'https://intensoperfumesfiles.s3.eu-central-1.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 9,
    suffixLength: 10,
    priceList: 'PD',
    siteName: 'Intenso Perfumes',
    defaultDescription: 'Pide en nuestra web. Paga fácil con tarjeta o en efectivo.',
    defaultImage: 'https://www.intensoperfumeshn.com/logo.webp',
    targetUrl: 'https://www.intensoperfumeshn.com',
  },
  'kcarebeautyhn.com': {
    apiDomain: 'https://be.kcarebeautyhn.com/',
    s3Url: 'https://kcarefiles.s3.eu-central-1.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 9,
    suffixLength: 10,
    priceList: 'PD',
    siteName: 'KCareBeauty',
    defaultDescription: 'Pide en nuestra web, San Pedro y La Ceiba. Paga fácil con tarjeta o en efectivo. Disfruta con tu familia y amigos de nuestros productos.',
    defaultImage: 'https://kcarebeautyhn.com/logo.webp',
    targetUrl: 'https://kcarebeautyhn.com',
  },
  'tatoswings.hn': {
    apiDomain: 'https://tatos-api.aveapplications.com/',
    s3Url: 'https://tatosfiles.s3.eu-central-1.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 9,
    suffixLength: 10,
    priceList: 'PD',
    siteName: "Tato's Wings",
    defaultDescription: 'Pide en nuestra web o en el app Yuuju! en Tegucigalpa, San Pedro y La Ceiba. Paga fácil con tarjeta o en efectivo. Disfruta con tu familia y amigos de nuestros productos.',
    defaultImage: 'https://tatoswings.hn/logo.webp',
    targetUrl: 'https://tatoswings.hn',
  },
  'shopmukacafe.com': {
    apiDomain: 'https://cs-market.albatrosvirtual.com:93/',
    s3Url: 'https://mukacafefiles.s3.us-east-2.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 9,
    suffixLength: 10,
    priceList: 'MIN-PD',
    siteName: 'Muka Café',
    defaultDescription: 'Pide en nuestra web!. Paga fácil con tarjeta o en efectivo.',
    defaultImage: 'https://shopmukacafe.com/logo.webp',
    targetUrl: 'https://shopmukacafe.com',
  },
  'arbeautyhn.com': {
    apiDomain: 'https://market-pos.albatrosvirtual.com:83/',
    s3Url: 'https://arbeautyhnfiles.s3.eu-central-1.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 9,
    suffixLength: 10,
    priceList: '5696-PD',
    siteName: 'Arbeauty',
    defaultDescription: 'Tienda de Skincare Coreano & Japones Original en Honduras.',
    defaultImage: 'https://arbeautyhn.com/logo.webp',
    targetUrl: 'https://arbeautyhn.com',
  },
  'lira.hn': {
    apiDomain: 'https://cs-mp.albatrosvirtual.com:92/',
    s3Url: 'https://lirahnfiles.s3.us-east-2.amazonaws.com/folder',
    providerId: 1,
    prefixLength: 4, // -->  0001
    suffixLength: 15, // -> 000000000002202  --> 0001-000000000002202
    priceList: 'PD',
    siteName: 'Lira',
    defaultDescription: 'Pide en nuestra web o en nuestra app. Disfruta de gran variedad de productos.',
    defaultImage: 'https://lira.hn/logo.webp',
    targetUrl: 'https://lira.hn',
  },
};
